New update footer svg
PeterYurich/filmoteka_08 pull request #17
Opened 2022-08-25 22:06 UTC by TanichkaIs

New update footer svg

2022-08-25 22:08 UTC, TanichkaIs commented
New update footer svg

2022-08-25 22:17 UTC, PeterYurich requested changes

2022-08-25 22:17 UTC, PeterYurich commented on src/sass/layout/_footer.scss
> +body {
перемістити body в common

2022-08-25 22:17 UTC, PeterYurich commented on src/sass/layout/_footer.scss
> +  @media screen and (min-width: 768px) {
помістити селектори всередину медізапитів, поччинаючи з мобілки

2022-08-26 12:55 UTC, TanichkaIs commented on src/sass/layout/_footer.scss
> +body {
Done

2022-08-26 12:55 UTC, TanichkaIs commented on src/sass/layout/_footer.scss
> +  @media screen and (min-width: 768px) {
Done

2022-08-26 14:11 UTC, closed without merging