FT-16 start create modal
PeterYurich/filmoteka_08 pull request #3
Opened 2022-08-24 16:56 UTC by abeskhlibnova

2022-08-24 17:08 UTC, PeterYurich requested changes
svg-шку потім

2022-08-24 17:08 UTC, PeterYurich commented on src/partials/film-modal-window.html
> +        <img src="./images/Rectangle 18.jpg" class="modal__img" alt="${title}">
тут зайвий пробіл у імені картинка

2022-08-24 17:08 UTC, PeterYurich commented on src/sass/components/_film-modal-window.scss
> +    color: #ffffff;
кольори треба поставити через змінні

2022-08-24 17:08 UTC, PeterYurich commented on src/sass/components/_film-modal-window.scss
> +    font-weight: 500;
тут використай міксін  @include font(500, 12, 14);

2022-08-24 17:08 UTC, PeterYurich commented on src/sass/components/_film-modal-window.scss
> +    line-height: 1.33;
і тут міксін

2022-08-24 17:08 UTC, PeterYurich commented on src/sass/components/_film-modal-window.scss
> +    line-height: 1.33;
знов міксін

2022-08-24 17:08 UTC, PeterYurich commented on src/sass/components/_film-modal-window.scss
> +    color: #000000;
color через змінні

2022-08-24 17:08 UTC, PeterYurich commented on src/sass/components/_film-modal-window.scss
> +    font-weight: 500;
міксін

2022-08-24 17:08 UTC, PeterYurich commented on src/sass/components/_film-modal-window.scss
> +    font-weight: 500;
міксін

2022-08-24 17:08 UTC, PeterYurich commented on src/sass/components/_film-modal-window.scss
> +    color: #000000;
змінну

2022-08-24 17:08 UTC, PeterYurich commented on src/sass/components/_film-modal-window.scss
> +    color: #ffffff;
змінну

2022-08-24 23:04 UTC, abeskhlibnova commented on src/sass/components/_film-modal-window.scss
> +    color: #ffffff;
done

2022-08-24 23:27 UTC, PeterYurich requested changes

2022-08-24 23:27 UTC, PeterYurich commented on src/sass/components/_film-modal-window.scss
> +}
всі змінні вже є в файлику variables, а звідси їх треба буде прибрати

2022-08-24 23:27 UTC, PeterYurich commented on src/sass/components/_film-modal-window.scss
> +    transition: opacity 500ms cubic-bezier(0.4, 0, 0.2, 1), visibility 500ms cubic-bezier(0.4, 0, 0.2, 1);
в принципі, можна timingFunction теж використати з variables

2022-08-24 23:27 UTC, PeterYurich commented on src/sass/components/_film-modal-window.scss
> +.backdrop.is-hidden {
is-hidden есть прописанный в файле _visually-hidden

2022-08-24 23:27 UTC, PeterYurich commented on src/sass/components/_film-modal-window.scss
> +.backdrop.is-hidden {
только туда можешь дописать pointer-events: none;

2022-08-24 23:27 UTC, PeterYurich commented on src/sass/components/_film-modal-window.scss
> +    font-family: 'Roboto';
Roboto можно не указывать, т.к. он будет унаследован от body

2022-08-24 23:27 UTC, PeterYurich commented on src/sass/components/_film-modal-window.scss
> +    font-style: normal;
font-style: normal; - это же значение по умолчанию. Разве оно где-то изменялось?

2022-08-24 23:27 UTC, PeterYurich commented on src/sass/components/_film-modal-window.scss
> +    font-family: 'Roboto';
шрифт унаследуется

2022-08-24 23:27 UTC, PeterYurich commented on src/sass/components/_film-modal-window.scss
> +    font-style: normal;
нормал?

2022-08-24 23:27 UTC, PeterYurich commented on src/sass/components/_film-modal-window.scss
> +    font-family: 'Roboto';
шрифт

2022-08-24 23:27 UTC, PeterYurich commented on src/sass/components/_film-modal-window.scss
> +    font-style: normal;
нормал

2022-08-24 23:27 UTC, PeterYurich commented on src/sass/components/_film-modal-window.scss
> +    line-height: 1.67;
тут миксин лучше как и в других местах ты уже делала

2022-08-24 23:27 UTC, PeterYurich commented on src/sass/components/_film-modal-window.scss
> +    line-height: 1.67;
А и вообще тут же он уже есть на следующей строчке)))

2022-08-24 23:27 UTC, PeterYurich commented on src/sass/components/_film-modal-window.scss
> +    font-style: normal;
тоже шрифт и нормал

2022-08-24 23:27 UTC, PeterYurich commented on src/sass/components/_film-modal-window.scss
> +    color: #ffffff;
я вижу хекс. Нет переменной

2022-08-24 23:27 UTC, PeterYurich commented on src/sass/components/_film-modal-window.scss
> +
кнопочки еще без стилей

2022-08-24 23:27 UTC, PeterYurich commented on src/sass/components/_film-modal-window.scss
> +@media screen and (min-width: 1200px) {
у нас точка перелома 1280px

2022-08-24 23:28 UTC, abeskhlibnova commented on src/sass/components/_film-modal-window.scss
> +
на всякий случай добавила

2022-08-24 23:33 UTC, abeskhlibnova commented on src/sass/components/_film-modal-window.scss
> +.backdrop.is-hidden {
А можна я залишу? Бо воно працює, а якщо працює, то є добре!

2022-08-24 23:46 UTC, abeskhlibnova commented on src/sass/components/_film-modal-window.scss
> +    font-family: 'Roboto';
Він не прописан ще у змінних

2022-08-25 09:01 UTC, YevhenProkhorenko submitted a review, later dismissed

2022-08-25 12:44 UTC, merged